# .gitlint
# https://jorisroovers.com/gitlint/configuration/#the-gitlint-file
#
# All these sections are optional. Each section with the exception of [general] represents
# one rule and each key in it is an option for that specific rule.
#
# Rules and sections can be referenced by their full name or by id. For example
# section "[body-max-line-length]" could also be written as "[B1]". Full section names are
# used in here for clarity.
# Rule reference documentation: http://jorisroovers.github.io/gitlint/rules/
#
# Use 'gitlint generate-config' to generate a config file with all possible options
[general]
debug=true                            # enable debug mode (prints more output). Disabled by default.
staged=true                           # fetch additional meta-data from the local repository when manually passing commit message to gitlint via stdin or --commit-msg. Disabled by default
verbosity = 2                         # verbosity should be a value between 1 and 3, the commandline -v flags take precedence over this
ignore-stdin=true                     # ignore any data send to gitlint via stdin
ignore=title-trailing-punctuation, T3 # ignore certain rules (comma-separated list), you can reference them by their id or by their full name
ignore-merge-commits=true             # by default gitlint will ignore merge, revert, fixup and squash commits.
ignore-revert-commits=true
ignore-fixup-commits=true
ignore-squash-commits=true

# enable community contributed rules and others
# https://github.com/jorisroovers/gitlint/blob/main/docs/rules.md
contrib=contrib-title-conventional-commits,CC1,title-max-length,title-trailing-whitespace,title-trailing-punctuation,title-hard-tab,title-must-not-contain-word,title-leading-whitespace,body-max-line-length,body-trailing-whitespace,body-hard-tab,body-first-line-empty,body-min-length,ignore-by-title

[title-max-length]                    # configure the "title-max-length" rule
line-length=72                        # set the line-length it enforces to 72

[title-min-length]                    # enforce minimal length of a title
min-length=5

[title-must-not-contain-word]         # comma-separated list of words that should not occur in the title case insensitively
words=wip                             # ignored if the keyword occurs as part of a larger word (so "WIPING" will not cause a violation)

[title-match-regex]                   # python like regex (https://docs.python.org/3/library/re.html) that the commit-msg title must be matched to
regex=^US[0-9]*                       # note that the regex can contradict with other rules if not used correctly

[body-max-line-length]
line-length=120

[body-min-length]
min-length=5

[body-is-missing]                     # whether to ignore this rule on merge commits (which typically only have a title)
default = True
ignore-merge-commits=false

[ignore-by-title]                     # ignore rules for commits titles
regex=^(wip:|fix: Temp)(.*)^          # ignore certain rules for commits of which the title matches a regex
ignore=all                            # ignore certain rules - use 'all' to ignore all rules - also it can by id or by full name

[ignore-by-body]                      # ignore rules for commits bodies
# regex=(.*)release(.*)               # which maches a regex
ignore=all  # all rules               # by: all, id or full name - e.g. ignore=T1,body-min-length

[ignore-body-lines]                   # ignore certain lines in a commit body that match a regex
regex=^(- |Co-Authored-By)            # disabled by default - need to be explicitly enabled adding to the [general] > "contrib" option

# | build             \ Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
# | ci                \ Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
# | docs              \ Documentation only changes
# | feat              \ A new feature
# | fix               \ A bug fix
# | perf              \ A code change that improves performance
# | ref               \ A code change that neither fixes a bug nor adds a feature
# | style             \ Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
# | test              \ Ad
# | packaging         \ used for changes that change the npm package layout in all of our packages, e.g. public path changes, package.json changes done to all packages, d.ts file/format changes, changes to bundles, etc.
# | changelog         \ used for updating the release notes in CHANGELOG.md
# | aio               \ used for docs-app (angular.io) related changes within the /aio directory of the repo
# | none/empty string \ useful for style, test and refactor changes that are done across all packages (e.g. style: add missing semicolons)
# | animations        \
# | common            \
# | compiler          \
# | compiler-cli      \
# | core              \
# | elements          \
# | forms             \
# | http              \
# | router            \
# | service-worker    \
# | upgrade           \

# Exit codes
# 253	Wrong invocation of the gitlint command.
# 254	Something went wrong when invoking git.
# 255	Invalid gitlint configuration
