#!/bin/bash

root="$(pwd)"

puts() {
  echo "[SETUP] [$1] $2"
}
i() {
  puts "INFO" "$1"
}
e() {
  puts "ERROR" "$1"
}
w() {
  puts "WARN" "$1"
}

cleanup() {
  for file in .bashrc .bash_logout .oh-my-zsh .profile; do
    if [[ -f "${HOME:?}/$file" ]]; then
      rm -rf "${HOME:?}/$file"
      i "${HOME:?}/$file removed ✔︎"
    fi
  done
}

# Setup config files
setup_config() {
  # If the ~/.config directory exists
  if [[ -d "${HOME:?}/.config" ]]; then
    # Create a symlink for each directory in the config directory in the current ~/.config
    rm -rf "${HOME:?}/.config"
    i "${HOME:?}/.config removed ✔︎"
  fi
  # Create a symlink to the config directory
  ln -sf "${root:?}/config" "${HOME:?}/.config"
  i "${HOME:?}/.config symlinked to ${root:?}/config ✔︎"
}

setup_nvim() {
  # Check if nvim is installed
  if ! command -v "${HOME:?}/.local/share/mise/shims/nvim" &>/dev/null; then
    w "nvim is not installed, skipping nvim setup."
    return
  fi

  if [[ -d "${HOME:?}/.config/nvim" ]]; then
    cd "${HOME:?}/.config/nvim" &&
      "${HOME:?}/.local/share/mise/shims/nvim" --headless +verbose \
        +'Lazy! sync' \
        +'Lazy! clean' \
        +'Lazy! clear' \
        +'TSUpdateSync' \
        -c 'lua require("lazy").load({plugins = {"mason-lspconfig.nvim"}})' \
        -c 'MasonInstall ast-grep bash-language-server css-lsp diagnostic-languageserver docker-compose-language-service dockerfile-language-server eslint-lsp html-lsp json-lsp lua-language-server marksman neocmakelsp prettier pyright ruby-lsp shfmt stylua taplo vim-language-server vtsls yaml-language-server' +qa
  else
    w "nvim is not installed, skipping nvim setup."
  fi
}

# Setup ZSH
setup_zsh() {
  # Create the ~/.cache/zsh/compcache directory if it doesn't exist
  if [[ ! -d "${ZSH_CACHE_DIR:-${XDG_CACHE_HOME:-${HOME:?}/.cache}/zsh}/compcache" ]]; then
    mkdir -p "${ZSH_CACHE_DIR:-${XDG_CACHE_HOME:-${HOME:?}/.cache}/zsh}/compcache"
    i "${ZSH_CACHE_DIR:-${XDG_CACHE_HOME:-${HOME:?}/.cache}/zsh}/compcache created ✔︎"
  fi

  # Create symlinks for the ZSH config files
  for file in .zshenv .zprofile .zshrc; do
    if [[ -f "${HOME:?}/.config/zsh/$file" ]]; then
      ln -sf "${HOME:?}/.config/zsh/$file" "${HOME:?}/$file"
      i "${HOME:?}/.config/zsh/$file symlinked to ${HOME:?}/$file ✔︎"
    fi
  done
}

# Main function
main() {
  w "Cleaning up..."
  cleanup
  w "Setting up config..."
  setup_config
  w "Setting up ZSH..."
  setup_zsh
  w "Setting up nvim..."
  setup_nvim
  m "Done! ✔︎✔︎"
}

# Run the main function
main
