#!/bin/bash

root="$(pwd)"

cleanup() {
  for file in .bashrc .bash_logout .oh-my-zsh .profile; do
    if [[ -f "${HOME:?}/$file" ]]; then
      rm -rf "${HOME:?}/$file"
    fi
  done
}

# Setup config files
setup_config() {
  # If the ~/.config directory exists
  if [[ -d "${HOME:?}/.config" ]]; then
    # Create a symlink for each directory in the config directory in the current ~/.config
    rm -rf "${HOME:?}/.config"
  fi
  # Create a symlink to the config directory
  ln -sf "${root:?}/config" "${HOME:?}/.config"
}

# Setup ZSH
setup_zsh() {
  # Create the ~/.cache/zsh/compcache directory if it doesn't exist
  if [[ ! -d "${ZSH_CACHE_DIR:-${XDG_CACHE_HOME:-${HOME:?}/.cache}/zsh}/compcache" ]]; then
    mkdir -p "${ZSH_CACHE_DIR:-${XDG_CACHE_HOME:-${HOME:?}/.cache}/zsh}/compcache"
  fi

  # Create symlinks for the ZSH config files
  for file in .zshenv .zprofile .zshrc; do
    if [[ -f "${HOME:?}/.config/zsh/$file" ]]; then
      ln -sf "${HOME:?}/.config/zsh/$file" "${HOME:?}/$file"
    fi
  done
}

# Main function
main() {
  cleanup
  setup_config
  setup_zsh
}

# Run the main function
main
