#!/usr/bin/env zsh
# shellcheck shell=bash disable=SC2154,SC1073,SC1058,SC1072,SC1009,SC1036,SC2155,SC2034,SC2120

#? dots 0.1.0
#? License RIT (Robot Institute of Technology)
#? This is free software: you are free to change and redistribute it.
#? There is NO WARRANTY, to the extent permitted by law.
#? http://docopt.org · Command-line interface description language

##? Manage dotfiles
##?
##? Usage:
##?      dots [options]
##?
##? Arguments:
##?     env                   Shows environment variables.
##?     path                  Shows path.
##?     fpath                 Shows fpath.
##?     cdpath                Shows cdpath.
##?     zsh                   ZSH subcommands.
##?     palette               Print the ANSI color palette.
##?
##? Options:
##?     --benchmark           Benchmark ZSH startup time.
##?     --prof                Profilling ZSH.
##?
##? Examples:
##?     dots
##?     dots env
##?     dots path
##?     dots fpath
##?     dots cdpath
##?     dots palette
##?     dots zsh --benchmark [ measure | store | logs ]
##?     dots zsh --prof [ exec | store | stats | avg | logs ]
##?     dots zsh --prof trace [ --once ]

dots() {
  case $1 in
    path) # Print the path
      echo "$PATH" | sed 's/:/\n/g' | uniq -c
      ;;
    fpath) # Print the fpath
      echo "${FPATH:?}" | sed 's/:/\n/g' | uniq -c
      ;;
    cdpath) # Print the cdpath
      echo "$CDPATH" | sed 's/:/\n/g' | uniq -c
      ;;
    env) # Print the environment variables
      env | sort | uniq | bat -l log
      ;;
    palette) # Print the ANSI color palette
      local lorem="Arma virumque cano Troiae qui primus ab oris"
      for i in {0..256}; do
        print -P -- "ANSI[${i}] ${FX[fg]:?}${i}m${lorem}${FX[none]}"
      done
      ;;
    zsh) # ZSH subcommands
      local ZSH_BENCHMARK_DIR="$ZDOTDIR/tmp"
      local ZSH_BENCHMARK_FILE="$ZSH_BENCHMARK_DIR/benchmarks.csv"
      local ZSH_PROF_FILE="$ZSH_BENCHMARK_DIR/prof.csv"
      local ZSH_STATS_FILE="$ZSH_BENCHMARK_DIR/startup.csv"
      local ZSH_STATS_TMP_FILE="$ZSH_BENCHMARK_DIR/startup.tmp"

      ensure_tmp_dir_and_files() {
        [[ ! -d "$ZSH_BENCHMARK_DIR" ]] && mkdir -p "$ZSH_BENCHMARK_DIR"
        [[ ! -f "$ZSH_PROF_FILE" ]] && echo "date,command,real,user,sys,total" >"$ZSH_PROF_FILE"
        [[ ! -f "$ZSH_BENCHMARK_FILE" ]] && echo "date,command,real,user,sys,total" >"$ZSH_BENCHMARK_FILE"
        [[ ! -f "$ZSH_STATS_FILE" ]] && touch "$ZSH_STATS_FILE"
      }

      get_valid_tmp_file() {
        local prefix="zsh_tmp_${RANDOM}"
        local tmp_file="${ZSH_BENCHMARK_DIR}/${prefix}_${1:-file.csv}"
        echo "$tmp_file"
      }

      case $2 in
        --benchmark) # Benchmark ZSH startup time
          ensure_tmp_dir_and_files
          case "$3" in
            measure) # Run the zsh benchmark measure using hyperfine
              local times=${#--times:-10}
              local shell_args=(-i -c)
              [[ "$*" =~ '--login' ]] && shell_args+=(-l)
              [[ "$*" =~ '--norc' || "$*" =~ '--no-rc' || "$*" =~ '--no-rcs' || "$*" =~ '--norcs' ]] && shell_args+=(--no-rcs)
              [[ "$*" =~ '--no-globalrcs' || "$*" =~ '--no-global-rcs' ]] && shell_args+=(--no-global-rcs)
              local current_date="$(date '+%d_%m_%Y_%H_%M_%S')"
              local tmp_file="$(get_valid_tmp_file "benchmark.csv")"
              local awk_command="
                        NR==2 {printf \"%s,%s,%0.6f,%0.6f,%0.6f,%0.6f,%0.6f,%0.6f,%0.6f\\n\",
                          date, \$1, \$2, \$3, \$4, \$5, \$6, \$7, \$8
                        }"

              hyperfine --warmup 10 --runs 100 "z_prof=3 $SHELL ${shell_args[*]} exit" --export-csv >(awk -F',' -v date="$current_date" "$awk_command" >"$tmp_file") &&
                puts "hyperfine --warmup 10 --runs 100 'z_prof=3 $SHELL ${shell_args[*]} exit' --export-csv >(awk -F',' -v date='$current_date' '$awk_command' >'$tmp_file')" --green

              (
                head -n 1 "$ZSH_BENCHMARK_FILE"
                cat "$tmp_file"
                tail -n +2 "$ZSH_BENCHMARK_FILE"
              ) >"${ZSH_BENCHMARK_FILE}.new"
              mv "${ZSH_BENCHMARK_FILE}.new" "$ZSH_BENCHMARK_FILE"
              rm "$tmp_file"

              if [[ ! "$*" =~ '--no-stdout' ]]; then
                dots zsh --benchmark logs
                return
              fi
              ;;
            store) # Store the zsh benchmark results into ~/.config/zsh/tmp/benchmarks.csv
              dots zsh --benchmark measure --no-login --no-stdout && dots zsh --benchmark measure --login --no-stdout
              ;;
            logs) # Print the zsh benchmark logs
              gum table --separator=',' --border='rounded' --print --file "$ZSH_BENCHMARK_FILE" ;;
            *) 
              dots zsh --benchmark "$(gum filter --limit=1 'logs' 'measure' 'store')" ;;
          esac 
          ;;
        --prof) # Profilling ZSH
          # https://medium.com/tarkalabs/optimize-zsh-fce424fcfd5
          # https://blog.jonlu.ca/posts/speeding-up-zsh
          # https://joshghent.com/zsh-speed
          case $3 in
            uptime) # run zsh 10x and exit (INTERNAL USE)
              local times=${#--times:-10}
              local shell_args=(-i -c)
              [[ "$*" =~ '--login' ]] && shell_args+=(-l)
              [[ "$*" =~ '--norc' || "$*" =~ '--no-rc' || "$*" =~ '--no-rcs' || "$*" =~ '--norcs' ]] && shell_args+=(--no-rcs)
              [[ "$*" =~ '--no-globalrcs' || "$*" =~ '--no-global-rcs' ]] && shell_args+=(--no-global-rcs)
              for _ in $(seq 1 "$times"); do time z_prof=3 $SHELL "${shell_args[@]}" exit 2>&1; done
              ;;
            once) # run zsh 10x and exit (INTERNAL USE)
              echo -e "$(dots zsh --prof uptime "${@:4}" 2>&1 >/dev/null)" 
              ;;
            measure) # run zsh 10x and exit (INTERNAL USE)
              dots zsh --prof once "${@:4}" | sed -E 's/(user|system|cpu| total)//g; s/^[ ]*//' | sed -E 's/[ ]+/\t/g' 
              ;;
            average) # run zsh 10x, exit and calculate the average for USER, SYSTEM, CPU and TOTAL (INTERNAL USE)
              dots zsh --prof measure |
                awk 'function format(value) { if (value >= 1) return sprintf("%.2fs ", value); else return sprintf("%.fms", (value*1000)); }
                            { user+=substr($1, 1, length($1)-1); sys+=substr($2, 1, length($2)-1); cpu+=substr($3, 1, length($3)-1); total+=$4; } END { print format(user/NR)" "format(sys/NR)" "sprintf("%.0f", cpu/NR)"% "format(total/NR) }' 
              ;;
            stats) # Prints the ZSH stats separated by USER, SYSTEM, CPU and TOTAL
              puts "| 0.05  |  0.05  |  95 % | 0.099 | *" --green && dots zsh --prof measure "${@:4}" | gum table --separator=$'\t' -p -c "USER,SYSTEM,CPU,TOTAL"
              ;;
            avg) # Prints the average of the ZSH stats
              dots zsh --prof average | gum table --separator=' ' -p -c "USER,SYSTEM,CPU,TOTAL" 
              ;;
            store) # Store the ZSH stats into ~/.config/zsh/tmp/prof.csv
              echo "$(date '+%d/%m/%Y %H:%M:%S'),dots zsh --prof average --no-globalrc --login,$(dots zsh --prof average --no-globalrc --login | sed 's/ /,/g')" >>"$ZSH_PROF_FILE" && \
                echo "$(date '+%d/%m/%Y %H:%M:%S1'),dots zsh --prof average --no-globalrc,$(dots zsh --prof average --no-globalrc | sed 's/ /,/g')" >>"$ZSH_PROF_FILE" 
              ;;
            logs) # List all the ZSH prof logs from ~/.config/zsh/tmp/prof.csv
              gum table --separator=',' --border='rounded' --print --file "$ZSH_PROF_FILE" 
              ;;
            exec) # Execute the ZSH zprof command
              z_prof=1 "$SHELL" -ilc exit 
              ;;
            trace) # Trace the ZSH Startup. Print commands and their arguments as they are executed. The output is preceded by the value of $PS4, formatted
              case $2 in
                --once) # Trace the ZSH Startup. Print commands and their arguments as they are executed once. The output is preceded by the value of $PS4, formatted
                  echo -e "$(z_prof=1 z_trace=1 dots trace 2>&1 >/dev/null)" 
                  ;;
                *) 
                  z_prof=1 z_trace=1 "$SHELL" -ilc exit 
                  ;;
              esac 
              ;;
            *)
              dots zsh --prof "$(gum filter --limit=1 'logs' 'stats' 'exec' 'store' 'avg' 'trace')" 
              ;;
          esac
          ;; 
      esac
      ;;
    *)
      dots "$(gum filter --limit=1 'path' 'fpath' 'cdpath' 'env' 'zsh' 'palette')" 
      ;;
  esac
}

dots "${@}"

# vi: set ft=sh:
